export const schoolData = [
  {
    id: 1,
    schoolLogo: '/images/unilag',
    schoolName: 'University of Lagos (UNILAG)',
    motto: 'In Deed and in Truth',
    portal: 'https://cilpu.unilag.edu.ng',
    availability: true,
  },
  {
    id: 2,
    schoolLogo: '/images/oau',
    schoolName: 'Obafemi Awolowo University (OAU)',
    motto: 'For Learning and Culture',
    portal: '#',
    availability: false,
  },
  {
    id: 3,
    schoolLogo: '/images/unn',
    schoolName: 'University of Nigeria, Nsukka (UNN)',
    motto: 'To Restore the Dignity of Man',
    portal: '#',
    availability: false,
  },
  {
    id: 4,
    schoolLogo: '/images/abu',
    schoolName: 'Ahmadu Bello University (ABU)',
    motto: 'The First Duty of Every University is the Search for and the Spread of Knowledge',
    portal: '#',
    availability: false,
  },
  {
    id: 5,
    schoolLogo: '/images/ui',
    schoolName: 'University of Ibadan (UI)',
    motto: ' Recte Sapere Fons (Latin for To think straight is the fount of knowledge)',
    portal: '#',
    availability: false,
  },
  {
    id: 6,
    schoolLogo: '/images/covenantUni',
    schoolName: 'Covenant University',
    motto: 'Raising a New Generation of Leaders',
    portal: '#',
    availability: false,
  },
  {
    id: 7,
    schoolLogo: '/images/futa',
    schoolName: 'Federal University of Technology, Akure (FUTA)',
    motto: 'Technology for Self Reliance',
    portal: '#',
    availability: false,
  },
  {
    id: 8,
    schoolLogo: '/images/unilorin',
    schoolName: 'University of Ilorin (UNILORIN)',
    motto: 'Probitas Doctrina',
    portal: '#',
    availability: false,
  },
  {
    id: 9,
    schoolLogo: '/images/unilorin',
    schoolName: 'University of Ilorin (UNILORIN)',
    motto: 'Probitas Doctrina',
    portal: '#',
    availability: false,
  },
  // {
  //   id: 10,
  //   schoolLogo: '/images/unilag',
  //   schoolName: 'University of Enugu (UNILAG)',
  //   motto: 'In Deed and in Truth',
  //   availability: true,
  // },
  // {
  //   id: 12,
  //   schoolLogo: '/images/oau',
  //   schoolName: 'Obafemi Awolowo University (OAU)',
  //   motto: 'For Learning and Culture',
  //   availability: false,
  // },
  // {
  //   id: 13,
  //   schoolLogo: '/images/unn',
  //   schoolName: 'University of Nigeria, Nsukka (UNN)',
  //   motto: 'To Restore the Dignity of Man',
  //   availability: false,
  // },
  // {
  //   id: 14,
  //   schoolLogo: '/images/abu',
  //   schoolName: 'Ahmadu Bello University (ABU)',
  //   motto: 'The First Duty of Every University is the Search for and the Spread of Knowledge',
  //   availability: false,
  // },
  // {
  //   id: 15,
  //   schoolLogo: '/images/ui',
  //   schoolName: 'University of Ibadan (UI)',
  //   motto: ' Recte Sapere Fons (Latin for To think straight is the fount of knowledge)',
  //   availability: false,
  // },
  // {
  //   id: 16,
  //   schoolLogo: '/images/covenantUni',
  //   schoolName: 'Covenant University',
  //   motto: 'Raising a New Generation of Leaders',
  //   availability: false,
  // },
  // {
  //   id: 17,
  //   schoolLogo: '/images/futa',
  //   schoolName: 'Federal University of Technology, Akure (FUTA)',
  //   motto: 'Technology for Self Reliance',
  //   availability: false,
  // },
  // {
  //   id: 18,
  //   schoolLogo: '/images/unilorin',
  //   schoolName: 'University of Ilorin (UNILORIN)',
  //   motto: 'Probitas Doctrina',
  //   availability: false,
  // },
  // {
  //   id: 19,
  //   schoolLogo: '/images/unilorin',
  //   schoolName: 'University of Schooly (UNILORIN)',
  //   motto: 'Probitas Doctrina',
  //   availability: false,
  // },
  // {
  //   id: 20,
  //   schoolLogo: '/images/unilag',
  //   schoolName: 'University of Enugu (UNILAG)',
  //   motto: 'In Deed and in Truth',
  //   availability: true,
  // },
  // {
  //   id: 21,
  //   schoolLogo: '/images/oau',
  //   schoolName: 'Obafemi Awolowo University (OAU)',
  //   motto: 'For Learning and Culture',
  //   availability: false,
  // },
  // {
  //   id: 22,
  //   schoolLogo: '/images/unn',
  //   schoolName: 'University of Nigeria, Nsukka (UNN)',
  //   motto: 'To Restore the Dignity of Man',
  //   availability: false,
  // },
  // {
  //   id: 23,
  //   schoolLogo: '/images/abu',
  //   schoolName: 'Ahmadu Bello University (ABU)',
  //   motto: 'The First Duty of Every University is the Search for and the Spread of Knowledge',
  //   availability: false,
  // },
  // {
  //     id: 24,
  //     schoolLogo: "/images/ui",
  //     schoolName: "University of Ibadan (UI)",
  //     motto: " Recte Sapere Fons (Latin for To think straight is the fount of knowledge)",
  //     availability: false,

  // },
  // {
  //     id: 25,
  //     schoolLogo: "/images/covenantUni",
  //     schoolName: "Covenant University",
  //     motto: "Raising a New Generation of Leaders",
  //     availability: false,

  // },
  // {
  //     id: 26,
  //     schoolLogo: "/images/futa",
  //     schoolName: "Federal University of Technology, Akure (FUTA)",
  //     motto: "Technology for Self Reliance",
  //     availability: false,

  // },
  // {
  //     id: 27,
  //     schoolLogo: "/images/unilorin",
  //     schoolName: "University of Ilorin (UNILORIN)",
  //     motto: "Probitas Doctrina",
  //     availability: false,

  // },
  // {
  //     id: 28,
  //     schoolLogo: "/images/unilorin",
  //     schoolName: "University of Ilorin (UNILORIN)",
  //     motto: "Probitas Doctrina",
  //     availability: false,

  // },
]
