const industries: string[] = [
  'Agriculture',
  'Banking/Finance',
  'Construction / Real Estate',
  'Consumer Services',
  'Consumer Products',
  'Conglomerates',
  'Entertainment',
  'Health Care',
  'Hospitality / Leisure',
  'ICT',
  'Natural Resources',
  'Media',
  'Oil & Gas',
  'Retail',
  'Technology',
  'Telecommunications / Networking',
  'Utilities',
  'Transportation',
  'Education / Training',
  'Legal Services',
  'Manufacturing & Industrial',
  'Nonprofit & Social Services',
  'Travel / Tourism',
  'Others',
]

export default industries
