/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    companies: CompanyAuthOperations;
    'departmental-coordinators': DepartmentalCoordinatorAuthOperations;
    students: StudentAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    admins: Admin;
    companies: Company;
    'departmental-coordinators': DepartmentalCoordinator;
    students: Student;
    'interview-invitations': InterviewInvitation;
    'internship-applications': InternshipApplication;
    employments: Employment;
    reports: Report;
    internships: Internship;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    admins: AdminsSelect<false> | AdminsSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    'departmental-coordinators': DepartmentalCoordinatorsSelect<false> | DepartmentalCoordinatorsSelect<true>;
    students: StudentsSelect<false> | StudentsSelect<true>;
    'interview-invitations': InterviewInvitationsSelect<false> | InterviewInvitationsSelect<true>;
    'internship-applications': InternshipApplicationsSelect<false> | InternshipApplicationsSelect<true>;
    employments: EmploymentsSelect<false> | EmploymentsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    internships: InternshipsSelect<false> | InternshipsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user:
    | (Admin & {
        collection: 'admins';
      })
    | (Company & {
        collection: 'companies';
      })
    | (DepartmentalCoordinator & {
        collection: 'departmental-coordinators';
      })
    | (Student & {
        collection: 'students';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CompanyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface DepartmentalCoordinatorAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface StudentAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
    email: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: string;
  name: string;
  phone?: string | null;
  picture?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: string;
  name: string;
  cac?: string | null;
  courseAreas: ('Mathematics' | 'Science' | 'History' | 'Engineering' | 'Arts')[];
  location: {
    longitude: number;
    latitude: number;
  };
  phone: string;
  hasSetPassword?: boolean | null;
  address?: string | null;
  website?: string | null;
  description?: string | null;
  image?: (string | null) | Media;
  resetPasswordOtpHash?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departmental-coordinators".
 */
export interface DepartmentalCoordinator {
  id: string;
  name: string;
  phone?: string | null;
  picture?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students".
 */
export interface Student {
  id: string;
  firstName: string;
  lastName: string;
  middleName?: string | null;
  matricNo: string;
  hasSetPassword?: boolean | null;
  dob: string;
  nationality: string;
  stateOfOrigin: string;
  homeAddress: string;
  gender: 'MALE' | 'FEMALE';
  course: string;
  level: string;
  internshipType: 'SIWES' | 'TEACHING PRACTICE';
  image?: (string | null) | Media;
  bankCode?: string | null;
  bankName?: string | null;
  accountNo?: string | null;
  resetPasswordOtpHash?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interview-invitations".
 */
export interface InterviewInvitation {
  id: string;
  student: string | Student;
  company: string | Company;
  message: string;
  dateTime: string;
  status?: ('pending' | 'accepted' | 'declined' | 'company accected' | 'company declined') | null;
  declineReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internship-applications".
 */
export interface InternshipApplication {
  id: string;
  student: string | Student;
  company: string | Company;
  internship?: (string | null) | Internship;
  letter: string;
  status?: ('pending' | 'cancelled' | 'approved' | 'student declined' | 'company declined') | null;
  interviewInvitation?: (string | null) | InterviewInvitation;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internships".
 */
export interface Internship {
  id: string;
  company: string | Company;
  postDescription: string;
  jobDescription: string;
  courseArea: ('Mathematics' | 'Science' | 'History' | 'Engineering' | 'Arts')[];
  applicants?: (string | Student)[] | null;
  deadline?: string | null;
  startDate: string;
  endDate: string;
  image?: (string | null) | Media;
  status?: ('open' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employments".
 */
export interface Employment {
  id: string;
  student: string | Student;
  company: string | Company;
  dateEnded?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: string;
  student: string | Student;
  title: string;
  details: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'admins';
        value: string | Admin;
      } | null)
    | ({
        relationTo: 'companies';
        value: string | Company;
      } | null)
    | ({
        relationTo: 'departmental-coordinators';
        value: string | DepartmentalCoordinator;
      } | null)
    | ({
        relationTo: 'students';
        value: string | Student;
      } | null)
    | ({
        relationTo: 'interview-invitations';
        value: string | InterviewInvitation;
      } | null)
    | ({
        relationTo: 'internship-applications';
        value: string | InternshipApplication;
      } | null)
    | ({
        relationTo: 'employments';
        value: string | Employment;
      } | null)
    | ({
        relationTo: 'reports';
        value: string | Report;
      } | null)
    | ({
        relationTo: 'internships';
        value: string | Internship;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admins';
        value: string | Admin;
      }
    | {
        relationTo: 'companies';
        value: string | Company;
      }
    | {
        relationTo: 'departmental-coordinators';
        value: string | DepartmentalCoordinator;
      }
    | {
        relationTo: 'students';
        value: string | Student;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'admins';
        value: string | Admin;
      }
    | {
        relationTo: 'companies';
        value: string | Company;
      }
    | {
        relationTo: 'departmental-coordinators';
        value: string | DepartmentalCoordinator;
      }
    | {
        relationTo: 'students';
        value: string | Student;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  picture?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  cac?: T;
  courseAreas?: T;
  location?:
    | T
    | {
        longitude?: T;
        latitude?: T;
      };
  phone?: T;
  hasSetPassword?: T;
  address?: T;
  website?: T;
  description?: T;
  image?: T;
  resetPasswordOtpHash?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departmental-coordinators_select".
 */
export interface DepartmentalCoordinatorsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  picture?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students_select".
 */
export interface StudentsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  middleName?: T;
  matricNo?: T;
  hasSetPassword?: T;
  dob?: T;
  nationality?: T;
  stateOfOrigin?: T;
  homeAddress?: T;
  gender?: T;
  course?: T;
  level?: T;
  internshipType?: T;
  image?: T;
  bankCode?: T;
  bankName?: T;
  accountNo?: T;
  resetPasswordOtpHash?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interview-invitations_select".
 */
export interface InterviewInvitationsSelect<T extends boolean = true> {
  student?: T;
  company?: T;
  message?: T;
  dateTime?: T;
  status?: T;
  declineReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internship-applications_select".
 */
export interface InternshipApplicationsSelect<T extends boolean = true> {
  student?: T;
  company?: T;
  internship?: T;
  letter?: T;
  status?: T;
  interviewInvitation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employments_select".
 */
export interface EmploymentsSelect<T extends boolean = true> {
  student?: T;
  company?: T;
  dateEnded?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  student?: T;
  title?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internships_select".
 */
export interface InternshipsSelect<T extends boolean = true> {
  company?: T;
  postDescription?: T;
  jobDescription?: T;
  courseArea?: T;
  applicants?: T;
  deadline?: T;
  startDate?: T;
  endDate?: T;
  image?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}